Add Elasticsearch integration
P3K-TEAM/backend pull request #11
Opened 2020-12-03 20:29 UTC by OliverKanat

2020-12-03 20:38 UTC, Scr0ll submitted a review, later dismissed

2020-12-09 15:49 UTC, MCFreddie777 requested changes
Reviewed. Can't see the changes tho, unless it's properly impelmented

2020-12-09 15:49 UTC, MCFreddie777 commented on antiplag/antiplag/documents.py
> +        # Name of the Elasticsearch index
Are you planning on implementing this as a part of this task? Or we can merge it and implement later?

2020-12-09 15:49 UTC, MCFreddie777 commented on antiplag/antiplag/documents.py
> +        fields = []
Missing empty line.

2020-12-09 16:37 UTC, MCFreddie777 commented on antiplag/antiplag/documents.py
> +        # Name of the Elasticsearch index
We agreed in Slack on implementing it in other task.

2020-12-09 16:37 UTC, MCFreddie777 approved these changes
Approved ✅

2020-12-09 16:38 UTC, merged