BE-45 Implement text extraction method from image files
P3K-TEAM/backend pull request #14
Opened 2020-12-04 10:53 UTC by MaliniakovaKarin

2020-12-04 12:53 UTC, KToldy submitted a review, later dismissed
Looks good, no remarks

2020-12-04 12:58 UTC, MCFreddie777 requested changes

2020-12-04 12:58 UTC, MCFreddie777 commented on README.md
> +Download and install tesseract (https://digi.bib.uni-mannheim.de/tesseract/).
### Installation

 - *Windows*:

   Download the precompiled file (_tesseract-ocr-w64-setup-v4.1.0.20190314.exe_) and install tesseract from 
   here : [https://digi.bib.uni-mannheim.de/tesseract/](https://digi.bib.uni-mannheim.de/tesseract/).
    Don't forget to place the installation path into PATH environment variable.

 - *Linux (Ubuntu, debian)*: 
   ```
   sudo apt-get install tesseract-ocr
   ```
 - *MacOS*:
   ```
   brew install tesseract
   ```

2020-12-04 12:58 UTC, MCFreddie777 commented on antiplag/.env.example
> +TESSERACT=C:\Program Files\Tesseract-OCR\tesseract.exe
I would name this variable `TESSERACT_PATH`

2020-12-04 12:58 UTC, MCFreddie777 commented on antiplag/nlp/text_preprocessing.py
> +from PIL import Image
I see you're importing pillow (or its slightly modified version - PIL) here, but it's not in requirements. Does it come with django by default or do we need to add it to requirements?

2020-12-04 12:58 UTC, MCFreddie777 commented on antiplag/nlp/text_preprocessing.py
Should we leave this blank line here? Is it indented?

2020-12-04 12:59 UTC, MCFreddie777 commented
Please don't forget to resolve conflicts.

2020-12-09 21:19 UTC, MCFreddie777 approved these changes

2020-12-09 21:22 UTC, OliverKanat approved these changes

2020-12-09 21:22 UTC, merged