BE-78 Fix text submission name
P3K-TEAM/backend pull request #31
Opened 2021-03-17 22:02 UTC by OliverKanat

2021-03-17 22:05 UTC, MCFreddie777 requested changes

2021-03-17 22:05 UTC, MCFreddie777 commented on antiplag/constants.py
> +TEXT_SUBMISSION_NAME = "Text submission"
No newline at the end of file

2021-03-17 22:18 UTC, MCFreddie777 approved these changes

2021-03-19 22:36 UTC, Hemii approved these changes

2021-03-20 14:41 UTC, merged