BE-77-Compare-Processed-Text
P3K-TEAM/backend pull request #49
Opened 2021-04-14 15:07 UTC by Scr0ll

2021-04-14 15:09 UTC, MCFreddie777 commented
Please resolve your conflicts.

2021-04-17 11:07 UTC, MCFreddie777 requested changes

2021-04-17 11:07 UTC, MCFreddie777 commented on nlp/elastic.py
> +            {"name": doc.name, "text": doc.text_raw, "elastic_id": doc.meta["id"], "text_preprocessed": doc.text_preprocessed}
Do  we need the `text` field here if we return the preprocessed text?

2021-04-17 11:07 UTC, MCFreddie777 commented on nlp/text_comparison.py
> +            ) * 100,
Please if you moved the multiplication in here, please remove the multiplication in tasks, because now its multiplied twice.

2021-04-17 11:07 UTC, MCFreddie777 commented on nlp/elastic.py
> +            MoreLikeThis(fields=["text_raw", "meta", "text_preprocessed"], like=document_text)
Please, fix and test the diff endpoint now, return preprocessed text there.

2021-04-18 21:47 UTC, MCFreddie777 requested changes
Left some comments, otherwise looks good to me. Whats the status of the preprocessing, is it all done?

Have you tested this code using both app and the http client (postman). Does it work okay in your opinion?

2021-04-18 21:47 UTC, MCFreddie777 commented on antiplag/views.py
> +            print(second_document_result)
Please remove this `print`

2021-04-18 21:47 UTC, MCFreddie777 commented on nlp/elastic.py
> +    class Index:
Add this to the top of the class please.

2021-04-18 21:47 UTC, MCFreddie777 commented on nlp/elastic.py
> +        name = 'documents'
Missing empty line at the end of the file.

2021-04-19 11:08 UTC, Scr0ll commented
> Left some comments, otherwise looks good to me. Whats the status of the preprocessing, is it all done?
> 
> Have you tested this code using both app and the http client (postman). Does it work okay in your opinion?
> 
> Also don't forget to reformat your code, the pipeline has failed on linting step.

everything looks fine. tested with postman and with frontend. processing takes few seconds but also works fine.

2021-04-19 18:51 UTC, MCFreddie777 approved these changes

2021-04-19 19:04 UTC, OliverKanat approved these changes

2021-04-19 19:05 UTC, merged